### PR TITLE
Fix struct parsing in C mode

### LINKED ISSUE #171: Simple struct in C mode throws a nullref
The following piece of C code throws an exception somewhere in the pinvoke generation process.

```c
typedef struct
{
  int a;
} b;
```

### PR DESCRIPTION
**Pull request by mjsabby**
Fixes #171

### CODE REVIEW

**Comment by tannergooding** [comment]
👍, could we get a small regression test for this scenario?

You'll probably just need to tweak https://github.com/microsoft/ClangSharp/blob/master/tests/ClangSharp.PInvokeGenerator.UnitTests/PInvokeGeneratorTest.cs#L29 to take in the command line args, defaulting `null` to mean `DefaultClangCommandLineArgs`.

**Comment by mjsabby** [comment]
@tannergooding oops, forgot to include it in the commit, it is as you recommended.

**Review by tannergooding — APPROVED** [review]

File: sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.VisitDecl.cs [hunk 1]
```diff
@@ -1096,7 +1099,7 @@ private void VisitRecordDecl(RecordDecl recordDecl)
                     VisitConstantArrayFieldDecl(recordDecl, constantArray);
                 }
 
-                if (hasVtbl)
+                if (cxxRecordDecl != null && hasVtbl)
```
Comment (tannergooding) [inline sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.VisitDecl.cs:1102]: just a note, `hasVtbl` shouldn't ever be `true` if `cxxRecordDecl` is null; so this isn't "strictly" needed.
